### PR TITLE
Add word wrapping to descriptions, fix being able to edit other's home icons

### PR DESCRIPTION
**Pull request by ApliNi**
Probably a bad implementation, but it has no bugs. :/

It can't recognize the space between words or the position of the period to wrap, I can't find any lib that can do it and output a list of strings

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Why not take a look at https://github.com/WiIIiam278/HuskHomes2/blob/828703411eaa15eb7a13948a35c12c840d8a40c0/common/src/main/java/net/william278/huskhomes/config/Locales.java#L152-L164C5
which uses commons-text's built-in word wrapping algorithm. I suggest we use this -- it's better that both plugins use the same thing anyway.

**Comment by ApliNi** [comment]
I tried this, but it is not suitable for use in the GUI, the line break will force the text style to be cleared after that, and only MD style `[](gray)` can be used to restore it back

**Comment by ApliNi** [comment]
Added some minor fixes, this version can be released, since previous versions seem to be almost unusable

**Review by WiIIiam278 — APPROVED** [review]

**Comment by WiIIiam278** [comment]
> Added some minor fixes, this version can be released, since previous versions seem to be almost unusable

plan is to release this stuff in tandem with 1.20 tomorrow, ideally.

**Pull request merged**
