### PR TITLE
Re-customize the language file format and Update regular expression of the newline module

### PR DESCRIPTION
**Pull request by ApliNi**
I'm considering re-customizing the theme and color for the GUI, just like the picture in README.md, because the existing format and color are not suitable for the dark floating text box of the GUI.

Please reply if you agree and I will start updating the file.

### CODE REVIEW

**Comment by WiIIiam278** [comment]
Sure, so long as it works and generally looks nice and consistent. I do quite like the main green color, try and keep that in.

**Comment by ApliNi** [comment]
When I use green in hex here it will show up as blue, so I'll use "green" instead for now. Can you see the hex color in the GUI?

---

```yaml
item_name: '[%1%](#00fb9a)'
```
image

**Comment by ApliNi** [comment]
[HuskHomes] I found that the home with the same name can be generated by modifying the name. Directly creating a home with a duplicate name will prompt success but there is no new home. In the v4.3.2 version

**Comment by ApliNi** [comment]
Finished

**Pull request merged**
